from typing import Literal

RGBtype = tuple[int, int, int]
SceneType = Literal[
    "Alarm",
    "Bedtime",
    "Candlelight",
    "Christmas",
    "Cozy",
    "Cool white",
    "Daylight",
    "Diwali",
    "Deep dive",
    "Fall",
    "Fireplace",
    "Forest",
    "Focus",
    "Golden white",
    "Halloween",
    "Jungle",
    "Mojito",
    "Night light",
    "Ocean",
    "Party",
    "Pulse",
    "Pastel colors",
    "Plantgrowth",
    "Romance",
    "Relax",
    "Sunset",
    "Spring",
    "Summer",
    "Steampunk",
    "True colors",
    "TV time",
    "White",
    "Wake-up",
    "Warm white",
    "Rhythm",
]

